### PR TITLE
chore: cleanup

### PR DESCRIPTION
**Pull request by mvayngrib**
- add license
- simplify/upgrade linting setup

### CODE REVIEW

**Comment by RyanZim** [comment]
This should be edited for accuracy:
https://github.com/ExodusMovement/text-encoding-utf8/blob/74584a5aab96e7e8c61e40b97a005f91af2c1a19/test-legacy/utf8.js#L1-L4
Code there is under Unlicense or Apache 2.0: https://github.com/inexorabletash/text-encoding/blob/master/LICENSE.md

**Comment by mvayngrib** [comment]
@RyanZim do we also need to add their license to our license file? (How) do we merge those?

**Comment by RyanZim** [comment]
The Unlicense is intended to place the work in the public domain; I would just link to https://github.com/inexorabletash/text-encoding/blob/master/LICENSE.md in the comment instead of referencing LICENSE.md

**Comment by mvayngrib** [comment]
done f645a30daa668b2584

**Review by RyanZim — APPROVED** [review]
utACK

**Pull request merged**
